// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Platform.DataAccess.Postgress;

#nullable disable

namespace Platform.DataAccess.Postgress.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260403120000_AddStudentNumberAndAcademicDataJson")]
    partial class AddStudentNumberAndAcademicDataJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {

#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Platform.DataAccess.Postgress.AchievementConnetionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetId");

                    b.HasIndex("SourceId", "TargetId")
                        .IsUnique();

                    b.ToTable("achievement_connections", (string)null);
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.AchievementCriteriaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementID")
                        .HasColumnType("uuid");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AchievementID")
                        .IsUnique();

                    b.ToTable("achievement_criterias", (string)null);
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.AchievementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.ToTable("achievements", (string)null);
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.CourseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorEntity")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("PreviousID")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PreviousID");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.StudentAchievementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AchievementFoundDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AchievementGotDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AchievementID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFirstAnimationShown")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNotificationSeen")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AchievementID");

                    b.HasIndex("StudentID", "AchievementID")
                        .IsUnique();

                    b.ToTable("student_achievements", (string)null);
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.StudentEntity", b =>
                {
                    b.Property<string>("AcademicDataJson")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.AchievementConnetionEntity", b =>
                {
                    b.HasOne("Platform.DataAccess.Postgress.AchievementEntity", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Platform.DataAccess.Postgress.AchievementEntity", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.AchievementCriteriaEntity", b =>
                {
                    b.HasOne("Platform.DataAccess.Postgress.AchievementEntity", "Achievement")
                        .WithOne("Criteria")
                        .HasForeignKey("Platform.DataAccess.Postgress.AchievementCriteriaEntity", "AchievementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.AchievementEntity", b =>
                {
                    b.HasOne("Platform.DataAccess.Postgress.CourseEntity", "Course")
                        .WithMany("Achievements")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.CourseEntity", b =>
                {
                    b.HasOne("Platform.DataAccess.Postgress.CourseEntity", "PreviousCourse")
                        .WithMany()
                        .HasForeignKey("PreviousID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PreviousCourse");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.StudentAchievementEntity", b =>
                {
                    b.HasOne("Platform.DataAccess.Postgress.AchievementEntity", "Achievement")
                        .WithMany("StudentAchievements")
                        .HasForeignKey("AchievementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.DataAccess.Postgress.StudentEntity", "Student")
                        .WithMany("StudentAchievements")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.AchievementEntity", b =>
                {
                    b.Navigation("Criteria")
                        .IsRequired();

                    b.Navigation("StudentAchievements");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.CourseEntity", b =>
                {
                    b.Navigation("Achievements");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.StudentEntity", b =>
                {
                    b.Navigation("StudentAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
